version: '3'

services:
  app:
    container_name: flask_app
    build:
      context: ./app
      args:
        - platform=linux/amd64
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "5000"
    volumes:
      - ./app:/var/www/app

  nginx:
    container_name: flask_nginx
    build:
      context: ./nginx
      args:
        - platform=linux/amd64
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
