version: '3'

services:
  app:
    platform: linux/amd64
    container_name: flask_app
    build:
      context: ./app
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "5000"
    volumes:
      - ./app:/var/www/app

  nginx:
    platform: linux/amd64
    container_name: flask_nginx
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
