version: '3'

services:
  app:
    container_name: flask_app
    build: ./app
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "5000"
    volumes:
      - ./app:/var/www/app

  nginx:
    container_name: flask_nginx
    build: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
