version: '3'

services:
  app:
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/var/www/app/app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000

  nginx:
    environment:
      - SERVER_NAME=app_${COMPOSE_PROJECT_NAME}
    volumes:
      - ./nginx/config/nginx_flask.conf.templates:/etc/nginx/nginx.conf.templates
    command: /bin/sh -c "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.conf.templates > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
