version: '3'

services:
  app:
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/var/www/app/app.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000

  nginx:
    volumes:
      - ./nginx/config/nginx_flask.conf:/etc/nginx/nginx.conf
