version: '3'

services:
  app:
    platform: linux/amd64
    container_name: app_${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/python/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    expose:
      - "5000"
    volumes:
      - ../app:/var/www/app

  nginx:
    platform: linux/amd64
    container_name: nginx_${COMPOSE_PROJECT_NAME}
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
